name: Deploy to QA
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation. Trigger?

on:
  workflow_dispatch:
  # A push to main won't happen
  # push:
  #   branches: [ "main" ]
  pull_request:
    types: [closed]
  push:
    branches: [ "test" ]

run-name: 🤖 Build  ${{ github.repository }}  docker image by @${{ github.actor }}

jobs:
  prod-deployment:
    name: Deploys to qa 🚀, 💻, 🤖, 📦, 📝, 🧪, 🧑‍💻, 🌐, 📊, 🎉.
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: QA deploy
        run: |
            ls ${{ github.workspace }}
      - run: echo "🍏 @${{ github.actor }} This job's status is ${{ job.status }}."
